### ISSUE TITLE
Thunderbird 68 deactivated the Add-on for not being comaptible

### ISSUE THREAD

**Issue by plcstop** [otto802/quickarchiver#19]
My TB updated to 68.1.0 today. Afterwards many add-ons were deactivated for not being compatible with this version of Thunderbird.
Searching for Add-on updates and restart of TB fixed some but not quickarchiver.

Can we expect an update of quickarchiver or has the development been stopped?

**Comment by pvgang** [comment]
Yes. Please upgrade the add-on. I miss it.

**Comment by plcstop** [comment]
Works again - Thank you for the update!
