### ISSUE TITLE
Bug: QuickArchiver column no longer available from Thunderbord 78 on

### ISSUE THREAD

**Issue by dirvo** [otto802/quickarchiver#22]
Problem:

The column "QuickArchiver Folder" providing the link to the folder is no longer shown for the Inbox and is also not available in the drop-down allowing the selection of columns:

![image](https://user-images.githubusercontent.com/1919798/89990474-b9d7ac80-dc82-11ea-9bd4-c61e87d50864.png)

This happens on Windows 10 1909, Thunderbird 78.

This is the QuickArchiver version:
![image](https://user-images.githubusercontent.com/1919798/89990371-914fb280-dc82-11ea-9eae-09e96ac01397.png)

Expected behavior: The column appears in the drop-down, can be selected and then shows the link action to move the message to the folder.

**Comment by dirvo** [comment]
The issue is likely caused by the XUL changes coming with Thunderbird 78, see https://developer.thunderbird.net/add-ons/updating/tb78

**Comment by plcstop** [comment]
I have the same issue, but I saw it for the first time after the update to Tunderbird 78.2.2 (32-bit) on Window 10 Pro 1909. Build 18363.1016.
The add-on appears activated (Version 0.2.5, last updated Sept 23rd, 2019), but issues are the same as described by @dirvo above.
Restart of TB or Windows show no effect.

**Comment by zasran** [comment]
QuickArchiver is not compatible with Thunderbird 78, it's automatically disabled. Is there any chance it will be upgraded?

**Comment by otto802** [comment]
yep, I'm currently working on an upgrade. 

Some thunderbird apis (like notifications for msgsMoveCopyCompleted) seems not to work anymore, but the "new" MailExtension APIs bring a replacement: messages.onNewMailReceived.

So all in all I guess in the end to extension should be able to run again on TB78.

**Comment by otto802** [comment]
Hi, someone willing to test the 0.2.6. release candidate? On my macos 10.15.7 with Thunderbird 78.5.1 it works well. No new features, just TB78 compatibility. 

https://github.com/otto802/quickarchiver/blob/master/builds/quickarchiver-0.2.6-rc1.xpi

**Comment by primehalo** [comment]
I'm trying it out. So far seems to be working well.

**Comment by patrykl** [comment]
No problems on Gentoo, TB 78.5.1. Thanks a lot!

**Comment by Yohan555** [comment]
Hi
It's working great on Win10 64.
You should just improve one thing :
If an email is flagged with any label (personal, important...) the link of the column is blue ("html default blue") instead of being white (I'm in dark mode). It should be a CSS problem.

Thanks again for the update !!

**Comment by plcstop** [comment]
Working like in the past on Win10/64 with TB78.5.1 32-bit. A big thanks from my side as well. I really missed it!

**Comment by otto802** [comment]
fixed the color when labels are beeing used. Will upload this now as an official addon update: https://github.com/otto802/quickarchiver/raw/master/builds/quickarchiver-0.2.6.xpi 

Lets hope it will be reviewed quickly ;-)
