### ISSUE TITLE
Restrictions of amount

### ISSUE THREAD

**Issue by Hotkeyharry** [otto802/quickarchiver#23]
Are there any restrictions regarding the amount of definitions, because I can't create any more, but I already have many definitions, probably around 100 or more. A complete reset didn't help either ?!

**Comment by otto802** [comment]
no, there should be no restriction regarding the amount (depends of the SQLite table limits). I got an email from another user some days ago who describes a similar issue (not be able to create rules anymore). Can you let me know on which platform you are and which version of thunderbird?

**Comment by Hotkeyharry** [comment]
Windows 10 Pro Version 1803, latest Thunderbird 78.6.1, today morning I could done a new definition to a new folder without problems, great. I have the impression, that when it doesn't work, these are old entries that I have already had, but are no longer in the definition/SQL. Hope you understand what I mean. Perhaps is it possible to repair/optimize the SQLite Table? Is that a way or workaround?
