### ISSUE TITLE
Merkt sich (seit einem TB-update?) plötzlich keine neuen Regeln mehr

### ISSUE THREAD

**Issue by afgcons** [otto802/quickarchiver#25]
Castor11 und ich:
hmm, merkt sich (seit einem TB-update?) plötzlich keine neuen Regeln mehr, früher festgelegte funktionieren hingegen ...

2021-06-06: Mit "DB Browser for SQLite" (https://sqlitebrowser.org/) habe ich nachgewiesen dass keine neue Regeln ins "quickarchiver.sqlite" geschrieben werden. Mit grösster Vorsicht habe ich danach mit "cut&paste" aus alten Regeln neue gebaut. Erfolg!

Castor11 and me:
hmm, remembers (since a TB-update?) suddenly no new rules, but earlier defined ones work ...

2021-06-06: With "DB Browser for SQLite" (https://sqlitebrowser.org/) I proved that no new rules are written to "quickarchiver.sqlite". With great care I built new rules from old ones with "cut&paste". Success!

**Comment by weinerg** [comment]
Auch bei mir ist dieser Effekt immer wieder vorhanden.
Einmal konnte ich es beheben, indem ich nicht nur beim Sammel Posteingang den QuickArchiver Ordner als Spalte hinzugefügt habe, sondern auch in allen Einzel Posteingängen. Dann funktionierte das merken von neuen Regeln wieder für ein paar Tage. 
Ohne bewusst etwas verändert zu haben, geht es derzeit wieder mal nicht. 
Alte Regeln bleiben aber erhalten und funktionieren auch bei mir.

**Comment by plcstop** [comment]
Ich habe das gleiche Problem. Ich habe aber noch eine Beobachtung gemacht:
Neue Regeln werden nur dann erstellt, wenn es für diesen Absender noch nie eine Regel gegeben hat.
Wenn eine Regel gelöscht wird, erscheint es mir so, als ob der Eintrag zwar geleert, aber die Regel nicht gänzlich gelöscht wird:
Klickt man rechts auf eine Nachricht, bei der man zuvor die Regel gelöscht hat, erscheint der Eintrag "QA Regel bearbeiten" immer noch schwarz und man kann die Dialogbox ohne Inhalt öffnen.
Bei Absendern, für die noch nie eine Regel definiert war, ist der Menüpunkt grau (zumindest war das früher mal so, im Augenblick finde ich kein Beispiel mehr, bei dem das so ist).

**Comment by otto802** [comment]
Will close this, might be a duplicate of #30 or not existing anymore in 2.0.0
