### ISSUE TITLE
Failed to initialize after TB update

### ISSUE THREAD

**Issue by otto802** [otto802/quickarchiver#28]
It seems to need another restart after TB updated. From time to time you also need to switch folders/accounts to make the colum appear again. Not yet reproducible.

**Comment by inmedias** [comment]
+1 
In most (but not all) cases when TB 102.1 starts, the column is gone. If it is there (or re-seelcted), it is often (but not always) empty. When it is empty, there are unknown circumstances that lead to a suddenly refilled QuickArchive column. Not yet reproducible.

**Comment by Yohan555** [comment]
I also lost column on updates on 3 different computers (Windows 10 Pro).
But main problem is that all rules are lost.
I tried to check quickarchiver.sqlite and all old rules are there.
Why are they ignored ?

Other bug : randomly for some senders, rule is never created after move. Is there a way to manually create a new rule ?

**Comment by otto802** [comment]
Hi, can confirm both bases. Rules where lost on my mac for for one of my email-account (not all of them). A quick look showed that the internal TB folder-id has changed after the update and therefore the folder-connection is lost. Not an easy fix :-(

The issue with randomly not created rule annoys me too. Will see if I can find the reason.

**Comment by Yohan555** [comment]
Yes, TB use to keep first server's host as ID. So if the host has changed in the past, TB just update the ID...
I had no problem with gmail/outlook mailboxes.

I edited quickarchiver.sqlite to change all folders value with new ID but it's ignored.
You spoke about a cache in another post. Isn't it linked ? Is it possible to force cache update ?

**Comment by otto802** [comment]
the cache is only active during runtime: a TB restart cleares it. I had problems in the past with editing rules in sqlite while TB is opened (and accessing the sqlite db). Editing the sqlite while TB is closed should work...

**Comment by Yohan555** [comment]
I well closed TB to edit sqlite file.
All rules have been corrected with good folder but they are ignored.
I created new rule to check the new folder is OK.
Is there another criteria that don't consider all the rules but just a part of them ?

**Comment by otto802** [comment]
no, not that I'm aware of. If the folder id is correct it should work...

**Comment by otto802** [comment]
One reason for not created rules is here: https://github.com/otto802/quickarchiver/issues/30

**Comment by otto802** [comment]
will close this for now, as it might be solved in 2.0.0 (WebExtension)
