### ISSUE TITLE
Rules cannot be deleted

### ISSUE THREAD

**Issue by nessimonsta** [otto802/quickarchiver#29]
Guten Tag,
seit einiger Zeit kann man eine Regel "scheinbar" bearbeiten, die Auswahl entfernen löscht die bestehende Regel aber nicht.
Vielen Dank für die Reparatur und freundliche Grüße
Nessimonsta

Good day,
since some time you can edit a rule, but the remove selection does not delete the existing rule.
Thank you for the repair and kind regards
Nessimonsta

**Comment by otto802** [comment]
Hi, fixed in 0.2.11. Currently waiting for approval at addons.thunderbird.net. Manual download here: https://github.com/otto802/quickarchiver/raw/master/builds/quickarchiver-0.2.11.xpi

**Comment by nessimonsta** [comment]
Thank you so much Otto802 for your quick response!
with 0.2.11 all works in order  :-)
