### ISSUE TITLE
QuickArchiver column keeps disappearing or is displayed empty

### ISSUE THREAD

**Issue by dirvo** [otto802/quickarchiver#31]
Since about a month or two ago I keep observing the following behavior:

I have my inbox set up to show the column "QuickArchiver Folder" to quickly move mails according to the rules. This column now randomly either disappears completely or it is still shown but no links are visible (the entire column appears empty/white as if there were no rules defined). 

In the latter situation (the QuickArchiver column being white), the folder links as still active, i.e. clicking on the empty/white field in the QuickArchiver column moves the message accordingly.

Unfortunately I do not have a repro as this seems happening randomly. Most of the time the column is just not there anymore when switching back to Thunderbird (which is usually running all the time in the background).

Any ideas or pointers how to troubleshoot this are highly appreciated.

For the record: 
I'm using Thunderbird 102.4.2 (32-bit) on Windows 10 with Quickarchiver 0.2.11

**Comment by gregerspoulsen** [comment]
I'm having the same issue on 102.6.1 and 0.2.11.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
I have the same issue in the INBOX folder ... however: if I change over to another folder and change back to the INBOX folder, then I need to select the QuickArchiver column again from the display list, then everything is back to normal. That works until I close TB, reopening TB requires the above procedure again. 
Using Ubuntu Linux 22.04 with a current TB.

**Comment by primehalo** [comment]
I've been having this happen as well. At first I though the column just disappeared whenever Thunderbird started up but that's not the case. The disappearing column seems random. It's easy enough to restore the column but still annoying. Happens on both my Windows 10 PC and Windows 11 laptop running TB 102.12.0.
