### ISSUE TITLE
diplaying in message column 

### ISSUE THREAD

**Issue by zotpros** [otto802/quickarchiver#37]
Thanks for a great app. I didn't realize how dependent I have become of it to help tame my email inbox. This is why I hate running updates on apps, because it breaks stuff that works or preferred by me. Then when Thunderbird forced (or by accident) an update, the world got more out of control.

I can't seem to find a way to add this app to show a column for messages that already have rules. In the previous version this made going through messages to archive them very quick. Now I have to go to each message before I have the option to archive it. If this is not yet implemented, it would be nice to have it back soon. Thanks.

**Comment by otto802** [comment]
please see #35

**Comment by zotpros** [comment]
Thanks for your quick reply.
