### ISSUE TITLE
Thunderbird 60?

### ISSUE THREAD

**Issue by primehalo** [otto802/quickarchiver#5]
Will you be updating this soon to work with Thunberbird 60?

**Comment by otto802** [comment]
added some compatibility fixes, new version pending at addons.thunderbird.net. Build: https://github.com/otto802/quickarchiver/blob/master/builds/quickarchiver-0.2.3.xpi

**Comment by otto802** [comment]
new version released: https://addons.thunderbird.net/de/thunderbird/addon/quickarchiver/
